// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://gvotnjldomlxuezwuptf.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imd2b3Ruamxkb21seHVlend1cHRmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQ4MDc5NjIsImV4cCI6MjA3MDM4Mzk2Mn0.2E01ewOEz1uJLhnEGeEtxN4auGR10EV5xF7PVVgpQSs";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});